server:
    port: 8080
spring:
  application:
    name: spring-microservice-archetype
openai:
  api:
    key: ${OPENAI_API_KEY:}
    url: https://api.openai.com/v1/responses
  model:
    name: gpt-3.5-turbo
